name: ffms_mobile
description: FFMS - Pocket Family Finance & AI Companion App
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.0
  intl: ^0.20.3
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  camera: ^0.11.0
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  fl_chart: ^0.68.0
  http: ^1.2.0
  flutter_tts: ^4.2.5
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
